name: Verify Arduino files
on: [ push ]
  
jobs:
  build:
    name: Verifying compilation of Arduino files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Compile Arduino Sketches
      uses: arduino/compile-sketches@v1.0.0
      with:
        fqbn: "arduino:avr:leonardo"
        enable-warnings-report: true
        sketch-paths: |
          "rf24n_sim_host"
          "rf24n_sim_peripheral"
        libraries: |
          - name: Keypad
          - source-url: https://github.com/FastLED/FastLED.git
          - source-url: https://github.com/nRF24/RF24.git
          - source-url: https://github.com/nRF24/RF24Network.git
          - source-url: https://github.com/MHeironimus/ArduinoJoystickLibrary.git
        cli-compile-flags: |
          - --export-binaries
          - --output-dir="./build"
        
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_output
        path: ./build # or path/to/artifact
