on: [push, pull_request]
name: Compiler
jobs:
  test:
    name: Test ${{ matrix.sketch }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch:
          [
            ./rf24n_sim_receiver/rf24n_sim_receiver,
            ./rf24n_sim_sender/rf24n_sim_sender
          ]
        board:
          [
            "Legion2:avr:leonardoclp"
          ]
    steps:
      - uses: actions/checkout@master
      - uses: arduino/setup-arduino-cli@v1.0.0
      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      - name: Install SparkFun boards
        if: contains(matrix.board, 'promicro')
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json
          arduino-cli core install SparkFun:avr@1.1.5 --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json
      - name: Install FastLED
        run: arduino-cli lib install FastLED
      - name: Install RF24 libs
        run: |
          arduino-cli lib install RF24Network
          arduino-cli lib install RF24
      - name: Build ${{ matrix.sketch }} for ${{ matrix.board }}
        run: arduino-cli compile --fqbn ${{ matrix.board }} ${{ matrix.sketch }} --libraries ../ --warnings more
